name: LiteXpansion
description: 黏液科技附加 物理科技 繁體翻譯版.
version: ${project.version}
api-version: 1.16
author: j3fftw
depend: [Slimefun]
softdepend: [SlimyTreeTaps]
main: dev.j3fftw.litexpansion.LiteXpansion